import Head from "next/head";
import { useState } from "react";

const API_BASE = "http://localhost:3001";

export default function Add() {
  const [title, setTitle] = useState("");
  const [cover, setCover] = useState("");

  const addSong = async () => {
    if (title && cover) {
      await fetch(API_BASE + "/song/new", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: title,
          cover: cover,
        }),
      });

      setTitle("");
      setCover("");
    }
  };

  return (
    <>
      <Head>
        <title>Queens Greatest hit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex  flex-col items-center">
        <h1 className="text-primary-100 font-bold text-xl mb-10">
          Add New Queen Song
        </h1>
        <div className="flex flex-col w-[40%]">
          <h2 className="text-primary-100 text-lg mb-5">Track Title: </h2>
          <input
            type="text"
            className="border-2 border-slate-700 rounded-md p-2 outline-none"
            onChange={(e) => setTitle(e.target.value)}
            value={title}
          />
          <h2 className="text-primary-100 text-lg my-5">Cover Url: </h2>
          <input
            type="text"
            className="border-2 border-slate-700 rounded-md p-2 outline-none"
            onChange={(e) => setCover(e.target.value)}
            value={cover}
          />

          <button
            onClick={addSong}
            className="bg-white text-primary-100 py-2 px-4 border-2 border-primary-100 rounded-md mt-10 w-40 mx-auto hover:bg-primary-100 hover:text-white"
          >
            ADD
          </button>
        </div>
      </div>
    </>
  );
}
