import TableRow from "@/components/TableRow";
import Head from "next/head";
import { useEffect, useState } from "react";

const API_BASE = "http://localhost:3001";

interface SongType {
  _id: string;
  title: string;
  cover: string;
  votes: number;
}

export default function Leaderboard() {
  const [songs, setSongs] = useState<SongType[] | []>();

  const GetSongs = () => {
    fetch(API_BASE + "/songs")
      .then((res) => res.json())
      .then((data) => setSongs(data))
      .catch((error) => console.error("Error: ", error));
  };

  useEffect(() => {
    GetSongs();
  }, []);

  console.log(songs);
  return (
    <>
      <Head>
        <title>Queens Greatest hit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-[80%] mx-auto border-2 border-slate-800 mb-10">
        {songs?.map((song) => (
          <TableRow
            key={song._id}
            title={song.title}
            cover={song.cover}
            votes={song.votes}
          />
        ))}
      </div>
    </>
  );
}
